---

  - name: install virtualenv
    become: true
    pip:
        name: virtualenv
        executable: "{{ pip2 }}"

  - name: create virtualenv and install pip requirements
    pip:
      virtualenv: "{{ venv }}"
      virtualenv_python: /usr/bin/python
      virtualenv_site_packages: yes
      requirements: "{{ app_directory }}/requirements.txt"

  - name: copy systemd script
    become: true
    template:
      src: data_process.service
      dest: /etc/systemd/system/data_process.service

  - name: start data_process and enable on boot
    become: true
    systemd:
      name: "{{ service_name }}"
      state: started
      enabled: yes

  - name: copy nginx config
    become: true
    template:
      src: data_process
      dest: /etc/nginx/sites-available/data_process

  - name: link nginx config
    become: true
    file:
      src: /etc/nginx/sites-available/data_process
      dest: /etc/nginx/sites-enabled/data_process
      state: link

  - name: restart nginx
    become: true
    systemd:
      name: nginx
      state: restarted
